spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_EMAIL}
    password: ${PASSWORD_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      auto-index-creation: true
    redis:
      host: redis-13074.c292.ap-southeast-1-1.ec2.cloud.redislabs.com
      port: 13074
      timeout: 5s
      password: ${PASSWORD_REDIS}
      username: ${USERNAME_REDIS}
  mongodb:
    uri: mongodb+srv://ldamthanh62:${PASSWORD_MONGODB}@cluster0.tg8mcdl.mongodb.net/elearning?appName=Cluster0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
