spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME_EMAIL}
    password: ${PASSWORD_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      auto-index-creation: true
    redis:
      host: localhost 
      port: 12000
      timeout: 5s
  mongodb:
    uri: mongodb+srv://ldamthanh62:${PASSWORD_MONGODB}@cluster0.tg8mcdl.mongodb.net/elearning?appName=Cluster0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
